SELECT * FROM nsuryapr.[State]
SELECT * FROM nsuryapr.Gender
SELECT * FROM nsuryapr.Country
SELECT * FROM nsuryapr.Address
SELECT * FROM nsuryapr.Person_Info
SELECT * FROM nsuryapr.StudentType
SELECT * FROM nsuryapr.StudentStatus
SELECT * FROM nsuryapr.StudentLevel
SELECT * FROM nsuryapr.Student
SELECT * FROM nsuryapr.College
SELECT * FROM nsuryapr.Race
SELECT * FROM nsuryapr.majorAndminor
SELECT * FROM nsuryapr.StudentConcentration
SELECT * FROM nsuryapr.CoverType
SELECT * FROM nsuryapr.InsuranceType
SELECT * FROM nsuryapr.Job_Type
SELECT * FROM nsuryapr.Benefits
SELECT * FROM nsuryapr.Job_Information
SELECT * FROM nsuryapr.Employee
SELECT * FROM nsuryapr.Employee_Benefits
SELECT * FROM nsuryapr.JobOfEmployee
SELECT * FROM nsuryapr.Buildings
SELECT * FROM nsuryapr.EquipmentInfo
SELECT * FROM nsuryapr.EnrollmentStatus
SELECT * FROM nsuryapr.Classroom
SELECT * FROM nsuryapr.SemesterType
SELECT * FROM nsuryapr.SemesterInfo
SELECT * FROM nsuryapr.DEPARTMENT
SELECT * FROM nsuryapr.CourseLevel
SELECT * FROM nsuryapr.CourseDetails
SELECT * FROM nsuryapr.Prereqs
SELECT * FROM nsuryapr.CourseTimings
SELECT * FROM nsuryapr.Course_schedule
SELECT * FROM nsuryapr.CourseEnrollment
SELECT * FROM nsuryapr.EmployeeAndCourse
